#define MK_KINETIC_SPEED
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MOVE_DELTA 50
#define MOUSEKEY_INITIAL_SPEED 600
#define MOUSEKEY_BASE_SPEED 8000
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 96